### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by RobWu** [sosedoff/capistrano-unicorn#28] opened 2012-08-15 11:30 UTC
The recent gem is not based on the newest source.

Would be great if you could release a new gem version.

**Comment by huerlisi** [comment] 2012-09-04 06:35
Been using the master branch for a while, and it's working great:-) No showstoppers in there, but some nice fixes for multistaging etc.

Would appreciate a new release, too.

Thanks for this great gem!

**Comment by salzig** [comment] 2012-10-16 14:08
Then maybe just release the new 0.2.0? Master Branch seem to be stable.

**Comment by sosedoff** [comment] 2012-10-18 00:19
I havent implemented few features i wanted, but i guess i can release and add it later. Should be up in a day or so.

**Comment by RobWu** [comment] 2012-11-16 14:00
Any news on the release date of the next version?

**Comment by ealden** [comment] 2012-11-17 03:18
@sosedoff what else haven't you implemented?  I just started using this gem and I think it works quite well, and am interested in helping in any way I can.

**Comment by kuroda** [comment] 2012-11-30 12:24
+1

**Comment by salzig** [comment] 2012-12-20 04:47
four months later, no change?

**Comment by fabn** [comment] 2013-01-04 15:52
+1

**Comment by beno** [comment] 2013-01-18 14:22
Aha! What gets installed is completely unlike master. Can you please release a new version. thanks.

**Comment by ku1ik** [comment] 2013-01-19 12:33
+1

**Comment by sosedoff** [comment] 2013-01-23 06:59
New release is coming this weekend. I stopped using capistrano and unicorn for a while, there are many reasons to that, but i'll test and check that everything works. 

Some of the problems i've experienced are related to worker freeze issue, which is a big deal when you're running a single server (~ 2GB ram) that has a `preload_app` strategy enabled. This causes an unexpected memory overhead like having a 2x amount of workers running at the same time. The system goes into huge overload and eventually eats up all available memory, jumping all over the swap buffer. Most problems are encountered on bigger apps that use lots of third-party API's, on smaller apps everything works smooth since there are not much to load into application.

**Comment by RobWu** [comment] 2013-01-23 10:51
Thanks.

Would be great if you could also look into #42, before publish the gem.

**Comment by tompata** [comment] 2013-02-07 16:49
Please release it, thanks

**Comment by aspiers** [comment] 2013-02-15 15:28
+1

**Comment by bobbrez** [comment] 2013-03-11 22:48
+1

**Comment by phillbaker** [comment] 2013-03-12 21:34
+1

**Comment by austinrfnd** [comment] 2013-03-18 17:58
Please release it... 0.1.6 is straight broken.  graceful does a USR2 which is a duplicate.  If this doesn't get released in the next week or two I will personally fork this and maintain a separate gem.

**Comment by aspiers** [comment] 2013-03-18 18:47
@austinrfnd that shouldn't be necessary.  If you are desperate to install from a gem, you can use [`specific_install`](https://rubygems.org/gems/specific_install) to install from your own github fork.  [Bundler also supports installing from github](http://akash.im/2012/06/05/bundler-new-github-option.html).

I have push access to this repository, but not to rubygems.org - hopefully @sosedoff can make a release but I suggest you pester him directly via email, since many people don't read their github notifications very carefully.

**Comment by sosedoff** [comment] 2013-03-18 18:51
Hey guys,

Im willing to do a release right away, but i havent gotten a chance to go over changes. 
@aspiers is it good to go?

**Comment by austinrfnd** [comment] 2013-03-18 18:53
@sosedoff we have been using master and it looks fine from where I'm standing.

**Comment by aspiers** [comment] 2013-03-19 09:51
@sosedoff I haven't reviewed all the changes since 0.1.6, but if 0.1.6 is known to be broken then given many people are clamouring for 0.1.7, I'd say go for it anyway :-) If there is a major problem then I'm sure we can fix quickly in 0.1.8 ...

**Comment by bobbrez** [comment] 2013-03-19 12:24
@sosedoff would it make sense to add @aspiers to rubygems, if he's willing?
This is a really useful gem and having you be the only one to gate seems
like it must be a pain for you.

Sent from my iPhone

On Mar 19, 2013, at 5:52 AM, Adam Spiers notifications@github.com wrote:

@sosedoff https://github.com/sosedoff I haven't reviewed all the changes
since 0.1.6, but if 0.1.6 is known to be broken then given many people are
loudly requesting 0.1.7 I'd say go for it anyway :-) If there is a major
problem then I'm sure we can fix quickly in 0.1.8 ...

—
Reply to this email directly or view it on
GitHubhttps://github.com/sosedoff/capistrano-unicorn/issues/28#issuecomment-15105537
.

**Comment by austinrfnd** [comment] 2013-03-19 15:18
I agree with @bobbrez that having a second contributor to the gem seems like a solid idea.  If @aspiers can't do it, I would volunteer myself to help up keep the gem.

**Comment by aspiers** [comment] 2013-03-19 15:22
@austinrfnd Thanks for the offer!  I don't have time to maintain it, but @sosedoff owns it so it's up to him anyway.

**Comment by phillbaker** [comment] 2013-03-21 16:39
Bumping on this again. We're using master in production - @sosedoff, @aspiers seems to have confirmed 0.1.7 is good to go. This might be work a minor point bump though :smile:

**Comment by beno** [comment] 2013-03-21 16:42
Unfortunately @sosedoff has already spoken and we won't hear from him for another three months or so :)

**Comment by sosedoff** [comment] 2013-03-21 16:46
Release 0.1.7 is up.

**Comment by sosedoff** [comment] 2013-03-21 16:47
Closing this. Lets keep discussions for 0.2.0 in a separate thread.

**Comment by beno** [comment] 2013-03-21 16:47
Thank you Dan.

**Closed as completed by sosedoff** 2013-03-21 16:47 UTC
